conda activate poppy-linux

python tile.py   data/districts/1001.gpkg    data/tiled
python tile.py   data/districts/109.gpkg    data/tiled
python tile.py   data/districts/1121.gpkg    data/tiled
python tile.py   data/districts/1212.gpkg    data/tiled
python tile.py   data/districts/1403.gpkg    data/tiled
python tile.py   data/districts/1612.gpkg    data/tiled
python tile.py   data/districts/1809.gpkg    data/tiled
python tile.py   data/districts/2011.gpkg    data/tiled
python tile.py   data/districts/2111.gpkg    data/tiled
python tile.py   data/districts/2405.gpkg    data/tiled
python tile.py   data/districts/2601.gpkg    data/tiled
python tile.py   data/districts/2902.gpkg    data/tiled
python tile.py   data/districts/3006.gpkg    data/tiled
python tile.py   data/districts/3204.gpkg    data/tiled
python tile.py   data/districts/3407.gpkg    data/tiled
python tile.py   data/districts/605.gpkg    data/tiled
python tile.py   data/districts/709.gpkg    data/tiled
python tile.py   data/districts/821.gpkg  data/tiled
python tile.py   data/districts/1002.gpkg    data/tiled
python tile.py   data/districts/1101.gpkg    data/tiled
python tile.py   data/districts/1122.gpkg    data/tiled
python tile.py   data/districts/1213.gpkg    data/tiled
python tile.py   data/districts/1404.gpkg    data/tiled
python tile.py   data/districts/1613.gpkg    data/tiled
python tile.py   data/districts/1810.gpkg    data/tiled
python tile.py   data/districts/2012.gpkg    data/tiled
python tile.py   data/districts/2201.gpkg    data/tiled
python tile.py   data/districts/2406.gpkg    data/tiled
python tile.py   data/districts/2602.gpkg    data/tiled
python tile.py   data/districts/2903.gpkg    data/tiled
python tile.py   data/districts/3007.gpkg    data/tiled
python tile.py   data/districts/3205.gpkg    data/tiled
python tile.py   data/districts/3408.gpkg    data/tiled
python tile.py   data/districts/606.gpkg    data/tiled
python tile.py   data/districts/710.gpkg    data/tiled
python tile.py   data/districts/822.gpkg  data/tiled
python tile.py   data/districts/1003.gpkg    data/tiled
python tile.py   data/districts/1102.gpkg    data/tiled
python tile.py   data/districts/1123.gpkg    data/tiled
python tile.py   data/districts/1214.gpkg    data/tiled
python tile.py   data/districts/1405.gpkg    data/tiled
python tile.py   data/districts/1614.gpkg    data/tiled
python tile.py   data/districts/1811.gpkg    data/tiled
python tile.py   data/districts/2013.gpkg    data/tiled
python tile.py   data/districts/2202.gpkg    data/tiled
python tile.py   data/districts/2407.gpkg    data/tiled
python tile.py   data/districts/2603.gpkg    data/tiled
python tile.py   data/districts/2904.gpkg    data/tiled
python tile.py   data/districts/3008.gpkg    data/tiled
python tile.py   data/districts/3206.gpkg    data/tiled
python tile.py   data/districts/3409.gpkg    data/tiled
python tile.py   data/districts/607.gpkg    data/tiled
python tile.py   data/districts/711.gpkg    data/tiled
python tile.py   data/districts/901.gpkg  data/tiled
python tile.py   data/districts/1004.gpkg    data/tiled
python tile.py   data/districts/1103.gpkg    data/tiled
python tile.py   data/districts/1124.gpkg    data/tiled
python tile.py   data/districts/1215.gpkg    data/tiled
python tile.py   data/districts/1406.gpkg    data/tiled
python tile.py   data/districts/1615.gpkg    data/tiled
python tile.py   data/districts/1812.gpkg    data/tiled
python tile.py   data/districts/2014.gpkg    data/tiled
python tile.py   data/districts/2203.gpkg    data/tiled
python tile.py   data/districts/2408.gpkg    data/tiled
python tile.py   data/districts/2604.gpkg    data/tiled
python tile.py   data/districts/2905.gpkg    data/tiled
python tile.py   data/districts/301.gpkg    data/tiled
python tile.py   data/districts/3207.gpkg    data/tiled
python tile.py   data/districts/401.gpkg    data/tiled
python tile.py   data/districts/608.gpkg    data/tiled
python tile.py   data/districts/801.gpkg    data/tiled
python tile.py   data/districts/902.gpkg  data/tiled
python tile.py   data/districts/1005.gpkg    data/tiled
python tile.py   data/districts/1104.gpkg    data/tiled
python tile.py   data/districts/1125.gpkg    data/tiled
python tile.py   data/districts/1216.gpkg    data/tiled
python tile.py   data/districts/1407.gpkg    data/tiled
python tile.py   data/districts/1701.gpkg    data/tiled
python tile.py   data/districts/1813.gpkg    data/tiled
python tile.py   data/districts/2015.gpkg    data/tiled
python tile.py   data/districts/2204.gpkg    data/tiled
python tile.py   data/districts/2409.gpkg    data/tiled
python tile.py   data/districts/2605.gpkg    data/tiled
python tile.py   data/districts/2906.gpkg    data/tiled
python tile.py   data/districts/302.gpkg    data/tiled
python tile.py   data/districts/3208.gpkg    data/tiled
python tile.py   data/districts/402.gpkg    data/tiled
python tile.py   data/districts/609.gpkg    data/tiled
python tile.py   data/districts/802.gpkg    data/tiled
python tile.py   data/districts/903.gpkg  data/tiled
python tile.py   data/districts/1006.gpkg    data/tiled
python tile.py   data/districts/1105.gpkg    data/tiled
python tile.py   data/districts/1126.gpkg    data/tiled
python tile.py   data/districts/1217.gpkg    data/tiled
python tile.py   data/districts/1501.gpkg    data/tiled
python tile.py   data/districts/1702.gpkg    data/tiled
python tile.py   data/districts/1814.gpkg    data/tiled
python tile.py   data/districts/2016.gpkg    data/tiled
python tile.py   data/districts/2205.gpkg    data/tiled
python tile.py   data/districts/2410.gpkg    data/tiled
python tile.py   data/districts/2701.gpkg    data/tiled
python tile.py   data/districts/2907.gpkg    data/tiled
python tile.py   data/districts/303.gpkg    data/tiled
python tile.py   data/districts/3209.gpkg    data/tiled
python tile.py   data/districts/403.gpkg    data/tiled
python tile.py   data/districts/610.gpkg    data/tiled
python tile.py   data/districts/803.gpkg    data/tiled
python tile.py   data/districts/904.gpkg  data/tiled
python tile.py   data/districts/1007.gpkg    data/tiled
python tile.py   data/districts/1106.gpkg    data/tiled
python tile.py   data/districts/1127.gpkg    data/tiled
python tile.py   data/districts/1301.gpkg    data/tiled
python tile.py   data/districts/1502.gpkg    data/tiled
python tile.py   data/districts/1703.gpkg    data/tiled
python tile.py   data/districts/1901.gpkg    data/tiled
python tile.py   data/districts/201.gpkg    data/tiled
python tile.py   data/districts/2301.gpkg    data/tiled
python tile.py   data/districts/2411.gpkg    data/tiled
python tile.py   data/districts/2702.gpkg    data/tiled
python tile.py   data/districts/2908.gpkg    data/tiled
python tile.py   data/districts/304.gpkg    data/tiled
python tile.py   data/districts/3210.gpkg    data/tiled
python tile.py   data/districts/404.gpkg    data/tiled
python tile.py   data/districts/611.gpkg    data/tiled
python tile.py   data/districts/804.gpkg    data/tiled
python tile.py   data/districts/905.gpkg  data/tiled
python tile.py   data/districts/1008.gpkg    data/tiled
python tile.py   data/districts/1107.gpkg    data/tiled
python tile.py   data/districts/1128.gpkg    data/tiled
python tile.py   data/districts/1302.gpkg    data/tiled
python tile.py   data/districts/1503.gpkg    data/tiled
python tile.py   data/districts/1704.gpkg    data/tiled
python tile.py   data/districts/1902.gpkg    data/tiled
python tile.py   data/districts/202.gpkg    data/tiled
python tile.py   data/districts/2302.gpkg    data/tiled
python tile.py   data/districts/2412.gpkg    data/tiled
python tile.py   data/districts/2703.gpkg    data/tiled
python tile.py   data/districts/2909.gpkg    data/tiled
python tile.py   data/districts/305.gpkg    data/tiled
python tile.py   data/districts/3211.gpkg    data/tiled
python tile.py   data/districts/405.gpkg    data/tiled
python tile.py   data/districts/612.gpkg    data/tiled
python tile.py   data/districts/805.gpkg  data/tiled
python tile.py   data/districts/1009.gpkg    data/tiled
python tile.py   data/districts/1108.gpkg    data/tiled
python tile.py   data/districts/112.gpkg    data/tiled
python tile.py   data/districts/1303.gpkg    data/tiled
python tile.py   data/districts/1504.gpkg    data/tiled
python tile.py   data/districts/1705.gpkg    data/tiled
python tile.py   data/districts/1903.gpkg    data/tiled
python tile.py   data/districts/203.gpkg    data/tiled
python tile.py   data/districts/2303.gpkg    data/tiled
python tile.py   data/districts/2413.gpkg    data/tiled
python tile.py   data/districts/2704.gpkg    data/tiled
python tile.py   data/districts/2910.gpkg    data/tiled
python tile.py   data/districts/306.gpkg    data/tiled
python tile.py   data/districts/3212.gpkg    data/tiled
python tile.py   data/districts/406.gpkg    data/tiled
python tile.py   data/districts/613.gpkg    data/tiled
python tile.py   data/districts/806.gpkg  data/tiled
python tile.py   data/districts/1010.gpkg    data/tiled
python tile.py   data/districts/1109.gpkg    data/tiled
python tile.py   data/districts/113.gpkg    data/tiled
python tile.py   data/districts/1304.gpkg    data/tiled
python tile.py   data/districts/1505.gpkg    data/tiled
python tile.py   data/districts/1706.gpkg    data/tiled
python tile.py   data/districts/1904.gpkg    data/tiled
python tile.py   data/districts/204.gpkg    data/tiled
python tile.py   data/districts/2304.gpkg    data/tiled
python tile.py   data/districts/2414.gpkg    data/tiled
python tile.py   data/districts/2705.gpkg    data/tiled
python tile.py   data/districts/2911.gpkg    data/tiled
python tile.py   data/districts/307.gpkg    data/tiled
python tile.py   data/districts/3213.gpkg    data/tiled
python tile.py   data/districts/407.gpkg    data/tiled
python tile.py   data/districts/614.gpkg    data/tiled
python tile.py   data/districts/807.gpkg  data/tiled
python tile.py   data/districts/1011.gpkg    data/tiled
python tile.py   data/districts/110.gpkg    data/tiled
python tile.py   data/districts/114.gpkg    data/tiled
python tile.py   data/districts/1305.gpkg    data/tiled
python tile.py   data/districts/1506.gpkg    data/tiled
python tile.py   data/districts/1707.gpkg    data/tiled
python tile.py   data/districts/1905.gpkg    data/tiled
python tile.py   data/districts/205.gpkg    data/tiled
python tile.py   data/districts/2305.gpkg    data/tiled
python tile.py   data/districts/2415.gpkg    data/tiled
python tile.py   data/districts/2706.gpkg    data/tiled
python tile.py   data/districts/2912.gpkg    data/tiled
python tile.py   data/districts/308.gpkg    data/tiled
python tile.py   data/districts/3301.gpkg    data/tiled
python tile.py   data/districts/408.gpkg    data/tiled
python tile.py   data/districts/615.gpkg    data/tiled
python tile.py   data/districts/808.gpkg  data/tiled
python tile.py   data/districts/1012.gpkg    data/tiled
python tile.py   data/districts/1110.gpkg    data/tiled
python tile.py   data/districts/115.gpkg    data/tiled
python tile.py   data/districts/1306.gpkg    data/tiled
python tile.py   data/districts/1507.gpkg    data/tiled
python tile.py   data/districts/1708.gpkg    data/tiled
python tile.py   data/districts/1906.gpkg    data/tiled
python tile.py   data/districts/206.gpkg    data/tiled
python tile.py   data/districts/2306.gpkg    data/tiled
python tile.py   data/districts/2416.gpkg    data/tiled
python tile.py   data/districts/2707.gpkg    data/tiled
python tile.py   data/districts/2913.gpkg    data/tiled
python tile.py   data/districts/309.gpkg    data/tiled
python tile.py   data/districts/3302.gpkg    data/tiled
python tile.py   data/districts/409.gpkg    data/tiled
python tile.py   data/districts/616.gpkg    data/tiled
python tile.py   data/districts/809.gpkg  data/tiled
python tile.py   data/districts/1013.gpkg    data/tiled
python tile.py   data/districts/1111.gpkg    data/tiled
python tile.py   data/districts/1201.gpkg    data/tiled
python tile.py   data/districts/1307.gpkg    data/tiled
python tile.py   data/districts/1601.gpkg    data/tiled
python tile.py   data/districts/1709.gpkg    data/tiled
python tile.py   data/districts/1907.gpkg    data/tiled
python tile.py   data/districts/207.gpkg    data/tiled
python tile.py   data/districts/2307.gpkg    data/tiled
python tile.py   data/districts/2501.gpkg    data/tiled
python tile.py   data/districts/2708.gpkg    data/tiled
python tile.py   data/districts/2914.gpkg    data/tiled
python tile.py   data/districts/3101.gpkg    data/tiled
python tile.py   data/districts/3303.gpkg    data/tiled
python tile.py   data/districts/501.gpkg    data/tiled
python tile.py   data/districts/617.gpkg    data/tiled
python tile.py   data/districts/810.gpkg  data/tiled
python tile.py   data/districts/1014.gpkg    data/tiled
python tile.py   data/districts/1112.gpkg    data/tiled
python tile.py   data/districts/1202.gpkg    data/tiled
python tile.py   data/districts/1308.gpkg    data/tiled
python tile.py   data/districts/1602.gpkg    data/tiled
python tile.py   data/districts/1710.gpkg    data/tiled
python tile.py   data/districts/2001.gpkg    data/tiled
python tile.py   data/districts/2101.gpkg    data/tiled
python tile.py   data/districts/2308.gpkg    data/tiled
python tile.py   data/districts/2502.gpkg    data/tiled
python tile.py   data/districts/2709.gpkg    data/tiled
python tile.py   data/districts/2915.gpkg    data/tiled
python tile.py   data/districts/3102.gpkg    data/tiled
python tile.py   data/districts/3304.gpkg    data/tiled
python tile.py   data/districts/502.gpkg    data/tiled
python tile.py   data/districts/618.gpkg    data/tiled
python tile.py   data/districts/811.gpkg  data/tiled
python tile.py   data/districts/1015.gpkg    data/tiled
python tile.py   data/districts/1113.gpkg    data/tiled
python tile.py   data/districts/1203.gpkg    data/tiled
python tile.py   data/districts/1309.gpkg    data/tiled
python tile.py   data/districts/1603.gpkg    data/tiled
python tile.py   data/districts/1711.gpkg    data/tiled
python tile.py   data/districts/2002.gpkg    data/tiled
python tile.py   data/districts/2102.gpkg    data/tiled
python tile.py   data/districts/2309.gpkg    data/tiled
python tile.py   data/districts/2503.gpkg    data/tiled
python tile.py   data/districts/2710.gpkg    data/tiled
python tile.py   data/districts/2916.gpkg    data/tiled
python tile.py   data/districts/3103.gpkg    data/tiled
python tile.py   data/districts/3305.gpkg    data/tiled
python tile.py   data/districts/503.gpkg    data/tiled
python tile.py   data/districts/619.gpkg    data/tiled
python tile.py   data/districts/812.gpkg  data/tiled
python tile.py   data/districts/101.gpkg    data/tiled
python tile.py   data/districts/1114.gpkg    data/tiled
python tile.py   data/districts/1204.gpkg    data/tiled
python tile.py   data/districts/1310.gpkg    data/tiled
python tile.py   data/districts/1604.gpkg    data/tiled
python tile.py   data/districts/1801.gpkg    data/tiled
python tile.py   data/districts/2003.gpkg    data/tiled
python tile.py   data/districts/2103.gpkg    data/tiled
python tile.py   data/districts/2310.gpkg    data/tiled
python tile.py   data/districts/2504.gpkg    data/tiled
python tile.py   data/districts/2801.gpkg    data/tiled
python tile.py   data/districts/2917.gpkg    data/tiled
python tile.py   data/districts/3104.gpkg    data/tiled
python tile.py   data/districts/3306.gpkg    data/tiled
python tile.py   data/districts/504.gpkg    data/tiled
python tile.py   data/districts/701.gpkg    data/tiled
python tile.py   data/districts/813.gpkg  data/tiled
python tile.py   data/districts/102.gpkg    data/tiled
python tile.py   data/districts/1115.gpkg    data/tiled
python tile.py   data/districts/1205.gpkg    data/tiled
python tile.py   data/districts/1311.gpkg    data/tiled
python tile.py   data/districts/1605.gpkg    data/tiled
python tile.py   data/districts/1802.gpkg    data/tiled
python tile.py   data/districts/2004.gpkg    data/tiled
python tile.py   data/districts/2104.gpkg    data/tiled
python tile.py   data/districts/2311.gpkg    data/tiled
python tile.py   data/districts/2505.gpkg    data/tiled
python tile.py   data/districts/2802.gpkg    data/tiled
python tile.py   data/districts/2918.gpkg    data/tiled
python tile.py   data/districts/3105.gpkg    data/tiled
python tile.py   data/districts/3307.gpkg    data/tiled
python tile.py   data/districts/505.gpkg    data/tiled
python tile.py   data/districts/702.gpkg    data/tiled
python tile.py   data/districts/814.gpkg  data/tiled
python tile.py   data/districts/103.gpkg    data/tiled
python tile.py   data/districts/1116.gpkg    data/tiled
python tile.py   data/districts/1206.gpkg    data/tiled
python tile.py   data/districts/1312.gpkg    data/tiled
python tile.py   data/districts/1606.gpkg    data/tiled
python tile.py   data/districts/1803.gpkg    data/tiled
python tile.py   data/districts/2005.gpkg    data/tiled
python tile.py   data/districts/2105.gpkg    data/tiled
python tile.py   data/districts/2312.gpkg    data/tiled
python tile.py   data/districts/2506.gpkg    data/tiled
python tile.py   data/districts/2803.gpkg    data/tiled
python tile.py   data/districts/2919.gpkg    data/tiled
python tile.py   data/districts/3106.gpkg    data/tiled
python tile.py   data/districts/3401.gpkg    data/tiled
python tile.py   data/districts/506.gpkg    data/tiled
python tile.py   data/districts/703.gpkg    data/tiled
python tile.py   data/districts/815.gpkg  data/tiled
python tile.py   data/districts/104.gpkg    data/tiled
python tile.py   data/districts/1117.gpkg    data/tiled
python tile.py   data/districts/1207.gpkg    data/tiled
python tile.py   data/districts/1313.gpkg    data/tiled
python tile.py   data/districts/1607.gpkg    data/tiled
python tile.py   data/districts/1804.gpkg    data/tiled
python tile.py   data/districts/2006.gpkg    data/tiled
python tile.py   data/districts/2106.gpkg    data/tiled
python tile.py   data/districts/2313.gpkg    data/tiled
python tile.py   data/districts/2507.gpkg    data/tiled
python tile.py   data/districts/2804.gpkg    data/tiled
python tile.py   data/districts/3001.gpkg    data/tiled
python tile.py   data/districts/3107.gpkg    data/tiled
python tile.py   data/districts/3402.gpkg    data/tiled
python tile.py   data/districts/507.gpkg    data/tiled
python tile.py   data/districts/704.gpkg    data/tiled
python tile.py   data/districts/816.gpkg  data/tiled
python tile.py   data/districts/105.gpkg    data/tiled
python tile.py   data/districts/1118.gpkg    data/tiled
python tile.py   data/districts/1208.gpkg    data/tiled
python tile.py   data/districts/1314.gpkg    data/tiled
python tile.py   data/districts/1608.gpkg    data/tiled
python tile.py   data/districts/1805.gpkg    data/tiled
python tile.py   data/districts/2007.gpkg    data/tiled
python tile.py   data/districts/2107.gpkg    data/tiled
python tile.py   data/districts/2401.gpkg    data/tiled
python tile.py   data/districts/2508.gpkg    data/tiled
python tile.py   data/districts/2805.gpkg    data/tiled
python tile.py   data/districts/3002.gpkg    data/tiled
python tile.py   data/districts/310.gpkg    data/tiled
python tile.py   data/districts/3403.gpkg    data/tiled
python tile.py   data/districts/601.gpkg    data/tiled
python tile.py   data/districts/705.gpkg    data/tiled
python tile.py   data/districts/817.gpkg  data/tiled
python tile.py   data/districts/106.gpkg    data/tiled
python tile.py   data/districts/1119.gpkg    data/tiled
python tile.py   data/districts/1209.gpkg    data/tiled
python tile.py   data/districts/1315.gpkg    data/tiled
python tile.py   data/districts/1609.gpkg    data/tiled
python tile.py   data/districts/1806.gpkg    data/tiled
python tile.py   data/districts/2008.gpkg    data/tiled
python tile.py   data/districts/2108.gpkg    data/tiled
python tile.py   data/districts/2402.gpkg    data/tiled
python tile.py   data/districts/2509.gpkg    data/tiled
python tile.py   data/districts/2806.gpkg    data/tiled
python tile.py   data/districts/3003.gpkg    data/tiled
python tile.py   data/districts/3201.gpkg    data/tiled
python tile.py   data/districts/3404.gpkg    data/tiled
python tile.py   data/districts/602.gpkg    data/tiled
python tile.py   data/districts/706.gpkg    data/tiled
python tile.py   data/districts/818.gpkg  data/tiled
python tile.py   data/districts/107.gpkg    data/tiled
python tile.py   data/districts/111.gpkg    data/tiled
python tile.py   data/districts/1210.gpkg    data/tiled
python tile.py   data/districts/1401.gpkg    data/tiled
python tile.py   data/districts/1610.gpkg    data/tiled
python tile.py   data/districts/1807.gpkg    data/tiled
python tile.py   data/districts/2009.gpkg    data/tiled
python tile.py   data/districts/2109.gpkg    data/tiled
python tile.py   data/districts/2403.gpkg    data/tiled
python tile.py   data/districts/2510.gpkg    data/tiled
python tile.py   data/districts/2807.gpkg    data/tiled
python tile.py   data/districts/3004.gpkg    data/tiled
python tile.py   data/districts/3202.gpkg    data/tiled
python tile.py   data/districts/3405.gpkg    data/tiled
python tile.py   data/districts/603.gpkg    data/tiled
python tile.py   data/districts/707.gpkg    data/tiled
python tile.py   data/districts/819.gpkg  data/tiled
python tile.py   data/districts/108.gpkg    data/tiled
python tile.py   data/districts/1120.gpkg    data/tiled
python tile.py   data/districts/1211.gpkg    data/tiled
python tile.py   data/districts/1402.gpkg    data/tiled
python tile.py   data/districts/1611.gpkg    data/tiled
python tile.py   data/districts/1808.gpkg    data/tiled
python tile.py   data/districts/2010.gpkg    data/tiled
python tile.py   data/districts/2110.gpkg    data/tiled
python tile.py   data/districts/2404.gpkg    data/tiled
python tile.py   data/districts/2511.gpkg    data/tiled
python tile.py   data/districts/2901.gpkg    data/tiled
python tile.py   data/districts/3005.gpkg    data/tiled
python tile.py   data/districts/3203.gpkg    data/tiled
python tile.py   data/districts/3406.gpkg    data/tiled
python tile.py   data/districts/604.gpkg    data/tiled
python tile.py   data/districts/708.gpkg    data/tiled
python tile.py   data/districts/820.gpkg  data/tiled